### ISSUE TITLE
OpenAPI with local reference doesn't work

### ISSUE THREAD

**Issue by Fyzu** [asyncapi/openapi-schema-parser#196] opened 2023-07-12 20:35 UTC
#### Describe the bug
I'm trying to run your example from the repository.

And I get errors like:
```js
  {
    code: 'asyncapi-document-resolved',
    message: '"message" property must have required property "oneOf"',
    path: [ 'channels', 'example', 'publish', 'message' ],
    severity: 0,
    range: { start: [Object], end: [Object] }
  },
  {
    code: 'asyncapi-document-resolved',
    message: '"message" property must match "then" schema',
    path: [ 'channels', 'example', 'publish', 'message' ],
    severity: 0,
    range: { start: [Object], end: [Object] }
  },
  {
    code: 'asyncapi-document-resolved',
    message: 'Property "schemaFormat" is not expected to be here',
    path: [ 'channels', 'example', 'publish', 'message', 'schemaFormat' ],
    severity: 0,
    range: { start: [Object], end: [Object] }
  },
  {
    code: 'asyncapi-document-resolved',
    message: 'Property "payload" is not expected to be here',
    path: [ 'channels', 'example', 'publish', 'message', 'payload' ],
    severity: 0,
    source: undefined,
    range: { start: [Object], end: [Object] }
  },
  {
    code: 'asyncapi-document-unresolved',
    message: 'Referencing in this place is not allowed',
    path: [ 'channels', 'example', 'publish', 'message', 'payload' ],
    severity: 0,
    range: { start: [Object], end: [Object] }
  },
```

#### How to Reproduce
Schema:
```yml
asyncapi: 2.0.0
info:
  title: Example with OpenAPI
  version: 0.1.0
channels:
  example:
    publish:
      message:
        schemaFormat: 'application/vnd.oai.openapi;version=3.0.0'
        payload:
          $ref: './openapi.yml#/components/schemas/Message'

```

#### Expected behavior
No errors

**Comment by derberg** [comment] 2023-08-09 14:26
@fmvilas @smoya hey folks, please have a look 🙏🏼

**Comment by smoya** [comment] 2024-03-11 17:41
As @jonaslagoni mentioned, the issue is with the schema of message in v2 that doesn't allow a reference object in the payload.

This is now fixed in v3, so please update your AsyncAPI documents

**Closed by smoya** 2024-03-11 17:41 UTC
Labels: bug
